# Generated by Django 4.2.2 on 2024-03-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fixed_price',
            field=models.BooleanField(),
        ),
    ]
