# Generated by Django 4.2.11 on 2024-04-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='catrgory',
            new_name='category',
        ),
    ]
